### ISSUE TITLE
Unable to compile using  jdk 1.8.0_40-ea

### ISSUE THREAD

**Issue by sreeraaman** [jidesoft/jidefx-oss#26]
Dear All,

I tried cloning the project and adjusted the jdk 8 path in gradle.properties and triggered the build on the root project folder (jidefx-oss). However, I get the following error.

/home/sriraman/jidefx-oss/module-fields/src/main/java/jidefx/scene/control/field/FormattedTextField.java:180: error: method getIndex in class TextFieldSkin cannot be applied to given types;
                HitInfo hitInfo = ((TextFieldSkin) getSkin()).getIndex(e);
                                                             ^
  required: double,double
  found: MouseEvent
  reason: actual and formal argument lists differ in length
/home/sriraman/jidefx-oss/module-fields/src/main/java/jidefx/scene/control/field/FormattedTextField.java:366: error: cancelEdit() in FormattedTextField cannot override cancelEdit() in TextInputControl
    public boolean cancelEdit() {
                   ^
  overridden method is final
Note: /home/sriraman/jidefx-oss/module-fields/src/main/java/jidefx/scene/control/field/popup/AbstractDatePopupContent.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
:module-fields:compileJava FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':module-fields:compileJava'.
  
  > Compilation failed; see the compiler error output for details.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

My Java Version:

java version "1.8.0_40-ea"
Java(TM) SE Runtime Environment (build 1.8.0_40-ea-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b15, mixed mode)

My Gradle Version:

---
## Gradle 2.1

Build time:   2014-09-08 10:40:39 UTC
Build number: none
Revision:     e6cf70745ac11fa943e19294d19a2c527a669a53

Groovy:       2.3.6
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_40-ea (Oracle Corporation 25.40-b15)
OS:           Linux 3.13.0-37-generic amd64

Can somebody please let me know what the issue is?

best regards
Sriraman.
